# Generated by Django 5.2.7 on 2025-10-14 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Electrodomestico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('cocina', 'Cocina'), ('limpieza', 'Limpieza'), ('climatización', 'Climatización'), ('cuidado_personal', 'Cuidado personal')], max_length=50)),
                ('tipo', models.CharField(choices=[('convencional', 'Convencional'), ('eficiente', 'Eficiente')], max_length=20)),
                ('potencia_w', models.FloatField()),
                ('horas_uso_diario', models.FloatField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TarifaEnergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_kwh', models.FloatField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalculoConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_mensual_kwh', models.FloatField()),
                ('consumo_anual_kwh', models.FloatField()),
                ('costo_mensual', models.FloatField()),
                ('costo_anual', models.FloatField()),
                ('huella_carbono_mensual', models.FloatField()),
                ('huella_carbono_anual', models.FloatField()),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('electrodomestico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calcuapp.electrodomestico')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calcuapp.tarifaenergia')),
            ],
        ),
    ]
